### ISSUE TITLE
Add tickets link to schedule when eventyay-tickets component is active

### ISSUE THREAD

**Issue by mariobehling** [fossasia/eventyay-talk#124]
The schedule does not have a link to the ticketing page when the eventyay-tickets SSO component is activated. 

1. Therefore add a ticket link into the schedule menu as shown below.
2. Show the menu "Schedule, Sessions, Speakers, Tickets" on the schedule, sessions, and speakers pages itself.

![Screenshot from 2024-07-16 00-13-10](https://github.com/user-attachments/assets/867cf66b-48bb-4d05-88e0-088c15a6e3f6)

**Comment by odkhang** [comment]
Hi @mariobehling, about the ticket ticket, I will add a input form under general setting of the event to input ticket url, is it okay?
