### ISSUE TITLE
Develop a component dashboard/landing page for Eventyay-Talk

### ISSUE THREAD

**Issue by AviGawande** [fossasia/eventyay-talk#131]
Right there is no module for start page where attendee/organizers will proceed for the event activities.
This is to achieve:

- starting page/dashboard for Eventyay-Talk.
- with support for installed Eventyay-components like(Eventyay-Tickets,Eventyay-Video).

**Comment by mariobehling** [comment]
Part of https://github.com/fossasia/eventyay-talk/issues/235
