### ISSUE TITLE
Development deployment does not display images and files

### ISSUE THREAD

**Issue by mariobehling** [fossasia/eventyay-talk#132]
The development deployment does not show speaker images, header images etc. and no files.

Compare: https://wikimania-dev.eventyay.com/wikimania-test/schedule/v/0.4/

![Screenshot from 2024-07-20 18-47-48](https://github.com/user-attachments/assets/00e09b97-41a0-4a74-b651-74e6f108db65)

**Comment by odkhang** [comment]
![image](https://github.com/user-attachments/assets/ea15a7ea-17a5-44ea-9353-101c3d05b347)

fixed by setup read permission for docker volumns folder: chmod 755 /var/lib/docker
