### ISSUE TITLE
Add online video link to menu

### ISSUE THREAD

**Issue by mariobehling** [fossasia/eventyay-talk#133]
Same as with online ticketing add an online video link.

compare https://github.com/fossasia/eventyay-talk/pull/128

**Comment by odkhang** [comment]
Hi @mariobehling, for showing online video button

1. if user not login, when redirect to video, favorite session won't be synced as we don't know where user coming from.
2. if user already login, when user redirect to video, they will see favorite they added from talk.

could you please confirm?

And now in talk component, there're 2 places allow user redirect to video.

1. if user is a speaker, they have a button on their profile, with traits (eventyay-video-event-{event short name}) which will be use for permission setting in video.

![image](https://github.com/user-attachments/assets/f541148b-2c9e-47ad-abce-df631f04a433)

2. a button in talk view, and no trail if user use this button, is it okay?

**Comment by mariobehling** [comment]
This button is ok, but the actual topic of this issue is to add the online video button to the "menu".

![image](https://github.com/user-attachments/assets/3bd3a4c6-6d52-4c2d-bcc5-faa52bc26d83)
