### ISSUE TITLE
PR deploy test deployment not working

### ISSUE THREAD

**Issue by mariobehling** [fossasia/eventyay-talk#144]
Error: [Push Docker image to Docker hub](https://github.com/fossasia/eventyay-talk/actions/runs/10073220822/job/27846795952#step:3:8)
Username and password required

![Screenshot from 2024-07-24 10-30-10](https://github.com/user-attachments/assets/7ed0d58e-e098-484d-8df2-4ed1fdc550d8)

**Comment by marcoag** [comment]
The secrets were wrong, fixed: https://github.com/fossasia/eventyay-talk/actions/runs/10079048138
