### ISSUE TITLE
Add button link to view or edit speaker profile

### ISSUE THREAD

**Issue by mariobehling** [fossasia/eventyay-talk#17]
After a speaker has submitted a proposal there is only a link to to edit or view the proposals, but there is no link to view or edit the speaker profile.

On the two related pages please add the button "View or edit speaker profile"

The logic is implemented. In the UI the feature is just hard to find for users. You can find it on the tiny button next to the user name. We need the box as mentioned in the issue.

Compare 
https://wikimania.eventyay.com/2024/cfp
https://wikimania.eventyay.com/2024/

![Screenshot from 2024-01-19 18-20-20](https://github.com/fossasia/eventyay-talk/assets/1583873/22b0671f-e5b9-4fc0-a281-1e7ced291204)
![Screenshot from 2024-01-19 18-20-00](https://github.com/fossasia/eventyay-talk/assets/1583873/f3fe4277-6461-4821-bed4-92919c8d72a1)

**Comment by jlin95** [comment]
Hi, I could take this up if it's still up for grabs.

**Comment by mariobehling** [comment]
Please go ahead and feel free to make a PR.
