### ISSUE TITLE
When a user is logged in or has a speaker account and tries to login with eventyay-tickets they receive "sign up"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/eventyay-talk#176]
When a user is logged in or has a speaker account and tries to login with eventyay-tickets they receive a "sign up" page and there is no way to go back or cancel sign up and login with another account.

They receive the info: You are about to use your Eventyay account to login, but your user info username / Email from Eventyay-Tickets already existed in our system. Please choose another username and Email.

Expected: There should be an option to link these two accounts.

![Screenshot from 2024-07-30 18-19-39](https://github.com/user-attachments/assets/5f00b56c-a990-423d-ae79-e1a39c07b7f5)

**Comment by Shruti-lab** [comment]
Hello @mariobehling! I would like to contribute to this issue. Could you guide me how should I go about this. Is there any installation guide?
