### ISSUE TITLE
Fix background color on login page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/eventyay-talk#238]
The login page that appears when logging in with eventyay-tickets has a blue background. Result is that only the white part of the logo appears properly. Show the background color in the default color same as the other backgrounds.

![Screenshot from 2024-11-29 09-06-22](https://github.com/user-attachments/assets/426fab1f-c3e8-40cc-8cd1-8b02a12fa8fc)

**Comment by JainamDosi** [comment]
HI, i would like to start contributing , how do i start?

**Comment by mariobehling** [comment]
Download the project and implement the changes. Then make a PR. Thanks
