### ISSUE TITLE
Call for speakers questionary ordering is broken

### ISSUE THREAD

**Issue by marcoag** [fossasia/eventyay-talk#47]
### Problem and impact

1. The order of questions on the admin page for a CfP is not respected. The speaker's form does show the correct order, but the CfP UI for the organiser does not.
2. The right-hand buttons do not align anymore as previously.
Needs investigation of what broke it.

Current UI
![Screenshot from 2024-02-18 10-10-41](https://github.com/fossasia/eventyay-talk/assets/1583873/c014b4e5-eb4e-4761-be84-f97bb7722f63)

Previously
![298150808-e092f505-9e85-4818-a8e6-73c79ba0deae](https://github.com/fossasia/eventyay-talk/assets/1583873/507a59df-8786-4313-a794-17d4415f241d)

**Comment by norbusan** [comment]
@HeinrichOlfert please go ahead!

**Comment by HeinrichOlfert** [comment]
okay, But I need a chating on https://app.gitter.im/#/room/#fossasia_fossasia:gitter.im

**Comment by mariobehling** [comment]
Solved by recent updates.
