### ISSUE TITLE
Anonymous users should see submit a proposal only

### ISSUE THREAD

**Issue by mariobehling** [fossasia/eventyay-talk#54]
### Problem and impact

Anonymous users currently see "edit or view proposals" an "view or edit speaker profile".

Expected for not-logged in anonymous users only the option "go to CfP" or "Submit a Proposal" should show up.

**Current**

![Screenshot from 2024-02-21 19-44-17](https://github.com/fossasia/eventyay-talk/assets/1583873/7c3df6b3-1592-4c7e-b3e6-980c75352490)
![Screenshot from 2024-02-21 19-43-46](https://github.com/fossasia/eventyay-talk/assets/1583873/4608dfc5-5dfb-4238-86ad-cc8f4353121e)

**Expected**

![Screenshot from 2024-02-21 19-59-07](https://github.com/fossasia/eventyay-talk/assets/1583873/cf515228-d0ca-4191-a026-9949908fea29)
![Screenshot from 2024-02-21 19-58-53](https://github.com/fossasia/eventyay-talk/assets/1583873/1fbb59c2-ce6b-43f7-9247-89d4450b8963)

**Comment by Dvinod28** [comment]
Hey @Darkboy17 I am interested in solving this problem, could you assign me ?
