### ISSUE TITLE
Emails are not following site design

### ISSUE THREAD

**Issue by mariobehling** [fossasia/eventyay-talk#79]
### Problem and impact

The system emails do not follow design specs as they have green elements instead of blue. Please change the style to match the blue website style.

![Screenshot from 2024-03-13 22-52-06](https://github.com/fossasia/eventyay-talk/assets/1583873/d9e09518-7e22-40be-8a24-85f5860a3118)

**Comment by cbum-dev** [comment]
![Screenshot from 2024-03-14 13-50-01](https://github.com/fossasia/eventyay-talk/assets/110410015/ee1ecb64-7e21-4184-8f0e-c1adc2915972)
Is the issue is still ongoing?

**Comment by mariobehling** [comment]
Ahh cool. Has been solved in the last update. Then closing it.
